version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management Plugin for debugging
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root!238Ji*"
      POSTGRES_DB: "atm"
  server:
    build:
      context: ./server # Context is root because of parent directory copy issues (wait-for-it.sh)
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    tty: true
    stdin_open: true